tmo/Controllers/KantarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using tmo.Models;
using tmo.Models.Login;

namespace tmo.Controllers
{
    [ControlLogin]
    public class KantarController : Controller
    {
        // GET: Kantar
        [HttpGet]
        [Authorize(Roles = "MudiListesi")]
        public ActionResult MudiListesi()
        {
            tmoEntities db = new tmoEntities();
            var vMudiler = db.mudiler.ToList();
            var vIller = db.iller.ToList();
            var vIlceler = db.ilceler.ToList();
            var vAraciKurumlar = db.mudi_araci_kurumlar.ToList();
            return View(Tuple.Create(vMudiler, vIller, vIlceler, vAraciKurumlar));
        }

        [HttpGet]
        [Authorize(Roles = "MudiKayit")]
        public ActionResult MudiKayit()
        {
            tmoEntities db = new tmoEntities();
            var vMudiler = db.mudiler.ToList();
            var vIller = db.iller.ToList();
            var vIlceler = db.ilceler.ToList();
            var vAraciKurumlar = db.mudi_araci_kurumlar.ToList();
            return View(Tuple.Create(vMudiler, vIller, vIlceler, vAraciKurumlar));
        }

        [HttpPost]
        [Authorize(Roles = "MudiKayit")]
        public ActionResult MudiKayit(mudiler yeniMudi, loglar islem)
        {
            tmoEntities db = new tmoEntities();
            var vMudiler = db.mudiler.Where(w=>w.vn_tc.Equals(yeniMudi.vn_tc) == true).FirstOrDefault();
            if (vMudiler == null)
            {
                islem.baslik = "Mudi Kaydı Ekledi.";
                islem.islem_tarihi = DateTime.Now;
                islem.kim_tarafindan = Convert.ToInt32(Session["kullanici_id"]);
                yeniMudi.kayit_tarihi = DateTime.Now;
                db.loglar.Add(islem);
                db.mudiler.Add(yeniMudi);
                db.SaveChanges();
                TempData["approval"] = "Mudi Kaydı Başarılı.";
            }
            else { TempData["rejection"] = "Mudi Kaydı Daha Önce Yapılmış!"; }
            return RedirectToAction("MudiKayit");
        }

        [HttpPost]
        [Authorize(Roles = "MudiKayit")]
        public ActionResult MudiGuncelle(mudiler gelenMudi, loglar islem)
        {
            try
            {
                tmoEntities db = new tmoEntities();
                var vHangiMudi = db.mudiler.Where(w => w.mudi_id == gelenMudi.mudi_id).FirstOrDefault();

                vHangiMudi.ad_soyad_ünvan = gelenMudi.ad_soyad_ünvan;
                vHangiMudi.vn_tc = gelenMudi.vn_tc;
                vHangiMudi.vd = gelenMudi.vd;
                vHangiMudi.il_id = gelenMudi.il_id;
                vHangiMudi.ilce_id = gelenMudi.ilce_id;
                vHangiMudi.acik_adres = gelenMudi.acik_adres;
                vHangiMudi.araci_kurum_id = gelenMudi.araci_kurum_id;
                vHangiMudi.kayit_tipi = gelenMudi.kayit_tipi;
                vHangiMudi.guncellemeTarihi = DateTime.Now;

                islem.baslik = vHangiMudi.mudi_id.ToString() + "ID numaralı Mudi Kaydını Güncelledi.";
                islem.islem_tarihi = DateTime.Now;
                islem.kim_tarafindan = Convert.ToInt32(Session["kullanici_id"]);
                db.loglar.Add(islem);

                db.SaveChanges();
                TempData["approval"] = "Güncelleme Tamamlandı.";
                return RedirectToAction("MudiKayit");
            }
            catch (Exception)
            {
                TempData["rejection"] = "Bir Hata Oluştu.";
                return RedirectToAction("MudiKayit");
            }
        }


        [HttpGet]
        [Authorize(Roles = "TartimYap")]
        public ActionResult TartimYap()
        {
            tmoEntities db = new tmoEntities();
            var vTarimlar = db.tartim_bilgileri.ToList();
            return View(Tuple.Create(vTarimlar));
        }

        [HttpPost]
        [Authorize(Roles = "TartimYap")]
        public ActionResult TartimYap(tartim_bilgileri yeniTartim, loglar islem)
        {
            try
            {
                tmoEntities db = new tmoEntities();
                islem.baslik = "Yeni Tartım Yaptı.";
                islem.islem_tarihi = DateTime.Now;
                islem.kim_tarafindan = Convert.ToInt32(Session["kullanici_id"]);

                yeniTartim.kaydeden_personel_id = Convert.ToInt32(Session["kullanici_id"]);
                yeniTartim.kayit_tarihi = DateTime.Now;

                db.loglar.Add(islem);
                db.tartim_bilgileri.Add(yeniTartim);
                db.SaveChanges();
                TempData["approval"] = "Tartım Bilgileri Kaydedildi.";
                return RedirectToAction("TartimYap");
            }
            catch (Exception)
            {
                TempData["rejection"] = "Bir Hata Oluştu!";
                return RedirectToAction("TartimYap");
            }
        }

        [HttpPost]
        [Authorize(Roles = "TartimYap")]
        public ActionResult TartimGuncelle(tartim_bilgileri gelenTartim, loglar islem)
        {
            try
            {
                tmoEntities db = new tmoEntities();

                var vHangiTartim = db.tartim_bilgileri.Where(w => w.tartim_id == gelenTartim.tartim_id).FirstOrDefault();

                islem.baslik = gelenTartim.tartim_id + "ID numaralı Tartım Bilgisini Güncelledi.";
                islem.islem_tarihi = DateTime.Now;
                islem.kim_tarafindan = Convert.ToInt32(Session["kullanici_id"]);


                vHangiTartim.arac_cinsi = gelenTartim.arac_cinsi;
                vHangiTartim.ilk_tartim = gelenTartim.ilk_tartim;
                vHangiTartim.ikinci_tartim = gelenTartim.ikinci_tartim;
                vHangiTartim.net_miktar = gelenTartim.net_miktar;
                vHangiTartim.giris_mi_cikis_mi = gelenTartim.giris_mi_cikis_mi;
                vHangiTartim.degistiren_personel_id = Convert.ToInt32(Session["kullanici_id"]);
                gelenTartim.degisim_tarihi = DateTime.Now;

                db.loglar.Add(islem);
                db.SaveChanges();
                TempData["approval"] = "Tartım Bilgileri Güncellendi.";
                return RedirectToAction("TartimYap");
            }
            catch (Exception)
            {
                TempData["rejection"] = "Bir Hata Oluştu!";
                return RedirectToAction("TartimYap");
            }
        }
    }
}

tmo/Views/Kantar/MudiListesi.cshtml
@model Tuple<List<tmo.Models.mudiler>, List<tmo.Models.iller>, List<tmo.Models.ilceler>, List<tmo.Models.mudi_araci_kurumlar>>
@{
    ViewBag.Title = "MudiListesi";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="col-xl-12 col-md-12">
    <div class="ms-panel">
        <div class="ms-panel-header">
            <h6>MUDİ LİSTESİ</h6>
        </div>
        <div class="ms-panel-body">
            <div class="table-responsive">
                <div id="data-table-1_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">
                    <div class="row" style="width:100%">
                        <div class="col-sm-12">
                            <table id="example" class="display" style="width:100%">
                                <thead>
                                    <tr>
                                        <th>Ad Soyad & Ünvan</th>
                                        <th>V.N & TCKN</th>
                                        <th>V.D</th>
                                        <th>İl - İlçe</th>
                                        <th>Açık Adres</th>
                                        <th>Aracı Kurum</th>
                                        <th>Kayıt Tipi</th>
                                        <th>Kayıt Tarihi</th>
                                        <th>İşlem</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model.Item1)
                                    {
                                        <tr>
                                            <td>@item.ad_soyad_ünvan</td>
                                            <td>@item.vn_tc</td>
                                            <td>@item.vd</td>
                                            <td>@item.iller.provinceName @item.ilceler.countyName</td>
                                            <td>@item.acik_adres</td>
                                            <td>@item.mudi_araci_kurumlar.araci_kurum_adi</td>
                                            <td>@item.kayit_tipi</td>
                                            <td>@item.kayit_tarihi</td>
                                            <td>
                                                <a href="#" class="badge badge-outline-warning" data-toggle="modal" data-target="#duzenle@(item.mudi_id)" style="color:#FDA600;font-size:14px"><i class="flaticon-pencil"></i> Düzenle</a>
                                            </td>
                                        </tr>
                                        <!-- Mudi Modal -->
                                        <div class="modal fade" id="duzenle@(item.mudi_id)" tabindex="-1" role="dialog" aria-labelledby="duzenle@(item.mudi_id)">
                                            <div class="modal-dialog modal-dialog-centered" role="document">
                                                <div class="modal-content">

                                                    <div class="modal-header bg-secondary">
                                                        <h5 class="modal-title has-icon text-white" id="NoteModal">@item.ad_soyad_ünvan - Düzenle</h5>
                                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                                    </div>

                                                    @using (Html.BeginForm("MudiGuncelle", "Kantar", FormMethod.Post, new { enctype = "multipart/form-data", @class = "needs-validation clearfix", @novalidate = "" }))
                                                    {
                                                        <div class="modal-body">
                                                            <div class="ms-form-group">
                                                                <label for="validationCustom18">Ad Soyad / Ünvan</label>
                                                                <input type="text" class="form-control" id="validationCustom18" name="ad_soyad_ünvan" value="@item.ad_soyad_ünvan" required="">
                                                                <div class="invalid-feedback">
                                                                    Lütfen Açık Adres Giriniz3.
                                                                </div>
                                                            </div>

                                                            <div class="ms-form-group">
                                                                <label for="validationCustom28">TCKN / Vergi Num.</label>
                                                                <input type="number" class="form-control" id="validationCustom20" name="vn_tc" value="@item.vn_tc" required="">
                                                                <div class="invalid-feedback">
                                                                    Lütfen Açık Adres Giriniz.
                                                                </div>
                                                            </div>

                                                            <div class="ms-form-group">
                                                                <label for="validationCustom29">Vergi Dairesi</label>
                                                                <input type="text" class="form-control" id="validationCustom21" name="vd" value="@item.vd">
                                                                <div class="invalid-feedback">
                                                                    Lütfen Açık Adres Giriniz.
                                                                </div>
                                                            </div>

                                                            <div class="ms-form-group">
                                                                <label for="validationCustom30">İl</label>
                                                                <select class="form-control" id="validationCustom30" name="il_id" required="">
                                                                    <option value="@item.iller.provinceId">@item.iller.provinceName</option>
                                                                    @foreach (var il in Model.Item2)
                                                                    {
                                                                        <option value="@il.provinceId">@il.provinceName</option>
                                                                    }
                                                                </select>
                                                                <div class="invalid-feedback">
                                                                    Lütfen Açık Adres Giriniz.
                                                                </div>
                                                            </div>
                                                            <div class="ms-form-group">
                                                                <label for="validationCustom31">İlçe</label>
                                                                <select class="form-control" id="validationCustom31" name="ilce_id" required="">
                                                                    <option value="@item.ilceler.countyId">@item.ilceler.countyName</option>
                                                                    @foreach (var ilce in Model.Item3)
                                                                    {
                                                                        <option value="@ilce.countyId">@ilce.countyName</option>
                                                                    }
                                                                </select>
                                                                <div class="invalid-feedback">
                                                                    Lütfen Açık Adres Giriniz.
                                                                </div>
                                                            </div>
                                                            <div class="ms-form-group">
                                                                <label for="validationCustom32">Açık Adres</label>
                                                                <textarea type="text" class="form-control" id="validationCustom32" name="acik_adres" required="">@item.acik_adres</textarea>
                                                                <div class="invalid-feedback">
                                                                    Lütfen Açık Adres Giriniz.
                                                                </div>
                                                            </div>
                                                            <div class="ms-form-group">
                                                                <label for="validationCustom45">İlçe</label>
                                                                <select class="form-control" id="validationCustom54" name="araci_kurum_id" required="">
                                                                    <option value="@item.araci_kurum_id">@item.mudi_araci_kurumlar.araci_kurum_adi</option>
                                                                    @foreach (var araci_kurum in Model.Item4)
                                                                    {
                                                                        <option value="@araci_kurum.araci_kurum_id">@araci_kurum.araci_kurum_adi</option>
                                                                    }
                                                                </select>
                                                                <div class="invalid-feedback">
                                                                    Lütfen Aracı Kurum Seçiniz.
                                                                </div>
                                                            </div>
                                                            <div class="ms-form-group">
                                                                <label for="validationCustom33">Kayıt Tipi</label>
                                                                <select class="form-control" id="validationCustom33" name="kayit_tipi" required="">
                                                                    <option value="@item.kayit_tipi">@item.kayit_tipi</option>
                                                                    <option value="Bireysel">Bireysel</option>
                                                                    <option value="Kurumsal">Kurumsal</option>
                                                                </select>
                                                                <div class="invalid-feedback">
                                                                    Lütfean Açık Adres Giriniz.
                                                                </div>
                                                            </div>
                                                            <input hidden name="mudi_id" value="@item.mudi_id" />
                                                        </div>
                                                        <div class="modal-footer">
                                                            <button type="button" class="btn btn-light" data-dismiss="modal">İptal</button>
                                                            <button type="submit" class="btn btn-secondary shadow-none">Güncelle</button>
                                                        </div>
                                                    }
                                                </div>
                                            </div>
                                        </div>
                                    }
                                </tbody>

                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>